### ISSUE TITLE
Adding brucella to default species

### ISSUE THREAD

**Issue by druvus** [adrlar/CanSNPer#7]
It would a nice improvement to include Brucella to the existing organisms that are included by default.

**Comment by druvus** [comment]
This was closed by #9

**Comment by standage** [comment]
It looks like #9 added the SNP and TREE files to the project root directory, but this data is not included in `CanSNPerDB.db`. I tried adding it myself, but the `--import_seq_file` doesn't seem to support multiple chromosomes/replicons per species. Can you provide an update to the `CanSNPerDB.db`, file or instructions for importing all the data?

**Comment by druvus** [comment]
See my answer at #28
